input.entity.path = src/main/resources/sql/entities
input.association.path = src/main/resources/sql/associations
output.entity.path = src/main/resources/output/entities
output.association.path  = src/main/resources/output/associations
filenames.entity.path = src/main/resources/filenames/entityOutputFileNames.txt
filenames.association.path = src/main/resources/filenames/associationOutputFileNames.txt